version: "3"
services:
  flask-app:
    build:
      context: ./checker
      dockerfile: Dockerfile.flask  # Use a separate Dockerfile for Flask
    container_name: flask_app
    ports:
      - "5000:5000"  # Flask running on port 5000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

  fastapi-app:
    build:
      context: ./checker
      dockerfile: Dockerfile.telebot_fastapi  # Use a separate Dockerfile for FastAPI
    container_name: telebot_fastapi_app
    ports:
      - "8000:8000"  # FastAPI running on port 8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - flask-fastapi-app

  ngrok:
    image: wernight/ngrok   # Official ngrok image
    container_name: ngrok
    ports:
      - "4040:4040"  # Expose ngrok's web interface
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}  # Ngrok authtoken for authentication
      NGROK_SUBDOMAIN: quality-indirectly-pig  # Custom subdomain
    command: ngrok http -subdomain=${NGROK_SUBDOMAIN} nginx:80  # Tunnel traffic from Nginx
    depends_on:
      - nginx

