FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy app code
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 for Flask app
EXPOSE 5000

# Command to run Flask app
CMD ["python", "-c", "from app import run_flask; run_flask()"]
